#' Plot predicted effects from bayesian DLNM (B-DLNM)
#'
#' Plot lag-specific, overall, slices, contour or 3D representations for predicted effects generated by `bcrosspred()`.
#' @param x An object of class `"bcrosspred"` (returned by [bcrosspred]).
#' @param ptype Character. Plot type: one of `"slices"`, `"3d"`, `"contour"` or `"overall"`.
#' @param var Numeric vector of predictor values for slices plot type (maximum length of 4).
#' @param lag Numeric vector of lags for slices plot type (maximum length of 4).
#' @param ci Character. How to plot credible intervals: one of `"area"`, `"bars"`, `"lines"`, `"sampling"` (draw a line for each posterior sample) or `"none"`. Default: `"area"`.
#' @param ci.arg List of graphical arguments for the plotting of credible intervals passed to [graphics::lines].
#' @param ci.level Numeric in (0,1). Credible interval level. Default will take the `ci.level` specified in `x`.
#' @param cumul Logical. If `TRUE` it will plot cumulative predictions (requires cumulative predictions in `x`).
#' @param exp Logical. When `TRUE` plot on the exponentiated effects. Default will be `TRUE` only if `model.link` is `log/logit` in `x`.
#' @param ... Additional graphical arguments passed to base plotting functions.
#'
#' @export
#'
#' @examples
#' # Set exposure-response and lag-response spline parameters
#'  dlnm_var <- list(
#'    var_prc = c(10, 75, 90),
#'    var_fun = "ns",
#'    lag_fun = "ns",
#'    max_lag = 21,
#'    lagnk = 3
#'  )
#'
#'
#' # Set cross-basis parameters
#'  argvar <- list(fun = dlnm_var$var_fun,
#'                 knots = stats::quantile(london$tmean,
#'                                  dlnm_var$var_prc/100, na.rm = TRUE),
#'                 Bound = range(london$tmean, na.rm = TRUE))
#'
#'  arglag <- list(fun = dlnm_var$lag_fun,
#'                 knots = dlnm::logknots(dlnm_var$max_lag, nk = dlnm_var$lagnk))
#'
#'  # Create crossbasis
#'  cb <- dlnm::crossbasis(london$tmean, lag = dlnm_var$max_lag, argvar, arglag)
#'
#'  # Seasonality of mortality time series
#'  seas <- splines::ns(london$date, df = round(8 * length(london$date) / 365.25))
#'
#'  # Prediction values (equidistant points)
#'  temp <- seq(round(min(london$tmean), 1), round(max(london$tmean), 1), by = 0.1)
#'
#'  # Fit the model
#'  mod <- bdlnm(mort_75plus ~ cb + factor(dow) + seas, basis = cb, data = london, family = "poisson")
#'
#'  # Prediction
#'  cpred <- bcrosspred(x, cb, at = temp)
#'
#'  # Perform the plots:
#'
#'  #Overall
#'   plot(cpred, "overall", xlab = "Temperature (ºC)", ylab = "Relative Risk", col = 4,
#'   main="Overall", log = "y")
#' #3-D plot
#'   plot(cpred, zlab = "Relative risk", col = 4, lphi = 60, cex.axis = 0.6,
#'   xlab = "Temperature (ºC)", main = "3D graph of temperature effect")
#'   #Contour
#'  plot(cpred, "contour", xlab = "Temperature (ºC)", ylab = "Lag", main="Contour plot")
#'  #Slices (for a high temperature)
#'  htemp <- 23
#'  plot(cpred , "slices", var = htemp, col=3, ylab="RR",
#'  main=paste0("Association for a high temperature (", htemp, "ºC)"))
#'  #Slices (for lag 0)
#'  plot(cpred , "slices", lag = 0, col=4, ylab="RR", main=paste0("Association at Lag 0"))
#'
#'
plot.bcrosspred <- function(x,
                            ptype,
                            var = NULL,
                            lag = NULL,
                            ci = "area",
                            ci.arg,
                            ci.level = x$ci.level,
                            cumul = FALSE,
                            exp = NULL,
                            ...) {

  ## ---------------------------
  ## Basic checks
  ## ---------------------------

  # Check x object
  if (missing(x) || !is.list(x) || !inherits(x, "bcrosspred")) {
    cli::cli_abort("{.arg x} must be a {.cls bcrosspred} object as returned by {.fn bcrosspred}.")
  }

  # Check ptype
  if (missing(ptype) || !ptype %in% c("slices", "3d", "contour", "overall")) {
    cli::cli_abort(
      "{.arg ptype} must be one of {.val 'slices'}, {.val '3d'}, {.val 'contour' } or {.val 'overall'}."
    )
  }

  # Check CI
  if (!ci %in% c("area", "bars", "lines", "sampling", "none")) {
    cli::cli_abort(
      "{.arg ptype} must be one of {.val 'area'}, {.val 'bars'}, {.val 'lines' } or {.val 'sampling'} or {.val 'none'}."
    )
  }

  if(missing(ci.arg)) {
    ci.arg <- list()
  } else if(!is.list(ci.arg)) {
    cli::cli_abort("{.arg ci.arg} must be a list.")
  }

  if(!is.numeric(ci.level) || ci.level>=1 || ci.level<=0) {
    cli::cli_abort("{.arg ci.level} must be numeric and between {.val 0} and {.val 1}.")
  }

  # Validate var & lag inputs for slices
  if (ptype == "slices") {
    if (is.null(var) && is.null(lag)) {
      cli::cli_abort(
        "At least one of {.arg var} or {.arg lag} must be supplied when {.arg ptype} = {.val 'slices'}."
      )
    }

    if (!is.null(var)) {
      if (!is.numeric(var)) {
        cli::cli_abort("{.arg var} must be numeric.")
      }
      if (length(var) > 4L) {
        cli::cli_abort("{.arg var} length must be <= 4.")
      }
      # Check that requested var values are present in predictions
      if (!all(var %in% x$predvar)) {
        cli::cli_abort("All {.arg var} values must be present in {.code x$predvar}.")
      }
    }

    if (!is.null(lag)) {
      if (!is.numeric(lag)) {
        cli::cli_abort("{.arg lag} must be numeric.")
      }
      if (length(lag) > 4L) {
        cli::cli_abort("{.arg lag} length must be <= 4.")
      }
      # check lag validity against predicted lags
      predlag <- seq(from = x$lag[1],
                     to = x$lag[2],
                     by = x$bylag)

      if (!all(lag %in% predlag)) {
        cli::cli_abort("All {.arg lag} values must be present in {.val predlag}.")
      }
    }

  }

  # decide whether to compute CI from matfit directly or use stored summaries
  ci_compute <- !identical(ci.level, x$ci.level)

  # exp
  if (!is.null(exp) && !is.logical(exp)) cli::cli_abort("{.arg exp} must be logical")

  ## ---------------------------
  ## Prepare data
  ## ---------------------------

  # exponentiate if requested or if detected model.link suggests it
  noeff <- 0L
  if ((is.null(exp) && !is.null(x$model.link) && x$model.link %in% c("log", "logit")) || (!is.null(exp) && exp)) {
    matfit <- if (!cumul) x$matRRfit else x$cumRRfit
    allfit <- x$allRRfit
    matfitsum <- if (!cumul) x$matRRfit.summary else x$cumRRfit.summary
    allfitsum <- x$allRRfit.summary
    noeff <- 1L
  } else {
    matfit <- if (!cumul) x$matfit else x$cumfit
    allfit <- x$allfit
    matfitsum <- if (!cumul) x$matfit.summary else x$cumfit.summary
    allfitsum <- x$allfit.summary
    noeff <- 0L
  }

  #Revisar: ensure par is restored on exit??

  ## ---------------------------
  ## Plot: slices
  ## ---------------------------
  if (ptype == "slices") {
    # graphical layout: one plot per requested var/lag value
    npanels <- length(var) + length(lag)

    # set frame and grey scale
    mar.old <- graphics::par()$mar
    mfrow.old <- graphics::par()$mfrow
    mgp.old <- graphics::par()$mgp
    grey <- grey(0.9)

    if (npanels > 1) {
      graphics::layout(matrix(1:npanels, ncol = sum(!is.null(var), !is.null(lag))))
      grey <- grey(0.8)
      graphics::par(mgp = c(2, 0.7, 0),
          mar = c(4.1, 4.1, 2.1, 1.1))
    }

    predlag <- seq(from = x$lag[1],
                   to = x$lag[2],
                   by = x$bylag)

    # medians: use stored summary
    matfitmed <- matrix(matfitsum[, "0.5quant"],
                        nrow = length(x$predvar),
                        ncol = length(predlag))

    # low / high intervals
    if (!ci_compute) {
      #use stored summary
      quantiles <- grep("quant$", colnames(matfitsum))
      matfitlow <- matrix(matfitsum[, utils::head(quantiles, 1)], length(x$predvar), length(predlag))
      matfithigh <- matrix(matfitsum[, utils::tail(quantiles, 1)], length(x$predvar), length(predlag))
    } else {
      #recompute quantiles again
      quantiles <- c((1 - ci.level) / 2, 1 - (1 - ci.level) / 2)
      matfitlow <- matrix(
        apply(matfit, 1, stats::quantile, probs = quantiles[1]),
        length(x$predvar),
        length(predlag)
      )
      matfithigh <- matrix(
        apply(matfit, 1, stats::quantile, probs = quantiles[2]),
        length(x$predvar),
        length(predlag)
      )
    }

    # plot by requested lags
    if (!is.null(lag)) {
      for (i in lag) {
        # find which blog corresponds to this lag
        ind <- seq(length(x$predvar) * (which(predlag == i) - 1) + 1,
                   length(x$predvar) * (which(predlag == i)),
                   by = 1)
        matfit_ind <- matrix(x$matfit[ind, ], length(x$predvar), ncol(x$matfit))

        # set default plot arguments
        plot.arg <- list(
          type = "l",
          xlab = "Var",
          ylab = "Outcome",
          ylim = c(min(matfit[ind, ], na.rm = TRUE), max(matfit[ind, ], na.rm = TRUE)),
          bty = "l"
        )

        if (npanels > 1L) plot.arg$cex.axis <- 0.7

        # merge user args
        plot.arg <- utils::modifyList(plot.arg, list(...))

        # set credible intervals arguments
        ci.list <- list(
          panel.first = call(
            "fci",
            ci = ci,
            x = x$predvar,
            y = matfit_ind,
            high = matfithigh[, which(predlag == i)],
            low = matfitlow[, which(predlag == i)],
            ci.arg,
            plot.arg,
            noeff = noeff
          )
        )

        plot.arg <- utils::modifyList(plot.arg, c(ci.list, list(
          x = x$predvar, y = matfitmed[, which(predlag == i)]
        )))

        col <- plot.arg$col

        if (npanels > 1) {
          plot.arg$main <- ""
          plot.arg$xlab <- "Var"
        }

        # plot
        do.call("plot", plot.arg)

        if (length(lag) > 1) graphics::mtext(paste("Lag =", i), cex = 0.8)

      }
    }

    # plot by requested predictor values (var)
    if (!is.null(var)) {
      for (i in var) {
        # indices for this var across lag blocks
        ind <- which(x$predvar == i) + length(x$predvar) * (0:(length(predlag) - 1L))

        matfit_ind <- matrix(matfit[ind, ], length(predlag), ncol(matfit))

        # set default plot arguments
        plot.arg <- list(
          type = "l",
          xlab = "Lag",
          ylab = "Outcome",
          ylim = c(min(matfit[ind, ], na.rm = TRUE), max(matfit[ind, ], na.rm = TRUE)),
          bty = "l"
        )

        if (npanels > 1L) plot.arg$cex.axis <- 0.7

        # merge user args
        plot.arg <- utils::modifyList(plot.arg, list(...))

        # set credible intervals arguments
        ci.list <- list(
          panel.first = call(
            "fci",
            ci = ci,
            x = predlag,
            y = matfit_ind,
            high = matfithigh[which(x$predvar == i), ],
            low = matfitlow[which(x$predvar == i), ],
            ci.arg,
            plot.arg,
            noeff = noeff
          )
        )

        plot.arg <- utils::modifyList(plot.arg, c(ci.list, list(x = predlag, y = matfitmed[which(x$predvar == i), ])))


        if (npanels > 1L) {
          plot.arg$main <- ""
          plot.arg$xlab <- "Lag"
        }

        # plot
        do.call("plot", plot.arg)

        if (length(lag) > 1) graphics::mtext(paste("Var =", var[i]), cex = 0.8)

      }
    }
    if (npanels > 1L) {
      graphics::par(mar = mar.old,
          mfrow = mfrow.old,
          mgp = mgp.old)
    }
  }

  ## ---------------------------
  ## Plot: overall
  ## ---------------------------

  if (ptype == "overall") {

    # set default values
    min_all <- min(allfit, na.rm = TRUE)
    max_all <- max(allfit, na.rm = TRUE)

    plot.arg <- list(
      type = "l",
      ylim = c(min_all, max_all),
      xlab = "Var",
      ylab = "Outcome",
      bty = "l"
    )

    # merge with user args
    plot.arg <- utils::modifyList(plot.arg, list(...))

    col <- plot.arg$col

    predlag <- seq(from = x$lag[1],
                   to = x$lag[2],
                   by = x$bylag)

    # medians: use stored summary
    allfitmed <- allfitsum[, "0.5quant"]

    # low / high intervals
    if (!ci_compute) {
      #use stored summary
      quantiles <- grep("quant$", colnames(allfitsum))
      allfitlow <- allfitsum[, utils::head(quantiles, 1)]
      allfithigh <- allfitsum[, utils::tail(quantiles, 1)]
    } else {
      #recompute quantiles again
      quantiles <- c((1 - ci.level) / 2, 1 - (1 - ci.level) / 2)
      allfitlow <- apply(allfit, 1, stats::quantile, probs = quantiles[1])
      allfithigh <- apply(allfit, 1, stats::quantile, probs = quantiles[2])
    }

    # set credible intervals arguments
    ci.list <- list(
      panel.first = call(
        "fci",
        ci = ci,
        x = x$predvar,
        y = allfit,
        high = allfithigh,
        low = allfitlow,
        ci.arg,
        plot.arg,
        noeff = noeff
      )
    )
    plot.arg <- utils::modifyList(plot.arg, c(ci.list, list(x = x$predvar, y = allfitmed)))

    # plot
    do.call("plot", plot.arg)

  }

  ## ---------------------------
  ## Plot: 3D
  ## ---------------------------

  if (ptype == "3d") {
    if (x$lag[1] == x$lag[2]) {
      cli::cli_abort("3D plot is not meaningful for unlagged associations (single lag).")
    }

    predlag <- seq(from = x$lag[1],
                   to = x$lag[2],
                   by = x$bylag)

    # get the median summary
    matfitmed <- matrix(matfitsum[, "0.5quant"], length(x$predvar), length(predlag))
    rownames(matfitmed) <- x$predvar
    colnames(matfitmed) <- outer("lag", predlag, paste, sep = "")

    # set plot defaults
    plot.arg <- list(
      ticktype = "detailed",
      theta = 210,
      phi = 30,
      xlab = "Var",
      ylab = "Lag",
      zlab = "Outcome",
      col = "lightskyblue",
      zlim = c(min(matfitmed, na.rm = TRUE), max(matfitmed, na.rm = TRUE)),
      ltheta = 290,
      shade = 1,
      r = sqrt(3),
      d = 5,
      border = NA
    )

    # merge with the user args
    plot.arg <- utils::modifyList(plot.arg, list(...))

    plot.arg <- utils::modifyList(plot.arg, list(
      x = x$predvar,
      y = predlag,
      z = matfitmed
    ))

    # plot
    do.call("persp", plot.arg)

  }

  ## ---------------------------
  ## Plot: Contour
  ## ---------------------------

  if (ptype == "contour") {
    if (x$lag[2] == 0) {
      cli::cli_abort("Contour plot is not meaningful for unlagged associations.")
    }

    predlag <- seq(from = x$lag[1],
                   to = x$lag[2],
                   by = x$bylag)

    # get the median summary
    matfitmed <- matrix(matfitsum[, "0.5quant"], length(x$predvar), length(predlag))
    rownames(matfitmed) <- x$predvar
    colnames(matfitmed) <- outer("lag", predlag, paste, sep = "")

    # set default values
    levels <- pretty(matfitmed, n = 20)
    col1 <- grDevices::colorRampPalette(c("blue", "white"))
    col2 <- grDevices::colorRampPalette(c("white", "red"))
    col <- c(col1(sum(levels < noeff)), col2(sum(levels > noeff)))
    graphics::filled.contour(
      x = x$predvar,
      y = predlag,
      z = matfitmed,
      col = col,
      levels = levels,
      ...
    )
  }

}
